spring:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@10.111.201.33:1551:btuata
    username: btuser
    password: btuser
    validationQuery: SELECT 1 FROM DUAL
  jpa:
    database: oracle
    show-sql: false
    hibernate:
      ddl-auto: none
      able_lazy_load_no_trans: true
      jdbc:
        time_zone: UTC
      event:
        merge:
          entity_copy_observer: allow
    properties:
       hibernate.jdbc.batch_size: 20 
  hikari:
    connection-timeout: 60000
    maximum-pool-size: 20
  main:
    allow-bean-definition-overriding: true

management:
  server:
    port: 8086
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health, metrics, info, prometheus, beans
  endpoint:
    health:
      show-details: always

server:
  port: 8083

logbook:
  include:
    - /**
  exclude:
    - /actuator/**
    - /swagger-ui.html/**
  filter.enabled: true
  format.style: http
  strategy: default
  obfuscate:
    parameters:
      - access_token
      - password
      - token
