spring:
management:
  server:
    port: 8085
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health, metrics, info, prometheus, beans
  endpoint:
    health:
      show-details: always

server:
  port: 8082

logbook:
  include:
    - /**
  exclude:
    - /actuator/**
    - /swagger-ui.html/**
  filter.enabled: true
  format.style: http
  strategy: default
  obfuscate:
    parameters:
      - access_token
      - password
      - token

