/*
SQLyog Professional v13.1.1 (64 bit)
MySQL - 10.4.13-MariaDB 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

insert into `curency_convertor_rule` (`id`, `created_by_user`, `created_datetime`, `updated_by_user`, `updated_datetime`, `curency_convertor_rule`, `currency_to`, `currency_from`, `date_created`, `is_enabled`, `last_updated`, `rule_from`, `rule_to`, `str_spare5val`, `module`, `module_status`) values('1','',NULL,NULL,NULL,NULL,'USD','PKR',NULL,'',NULL,'/','*',NULL,NULL,NULL);
insert into `curency_convertor_rule` (`id`, `created_by_user`, `created_datetime`, `updated_by_user`, `updated_datetime`, `curency_convertor_rule`, `currency_to`, `currency_from`, `date_created`, `is_enabled`, `last_updated`, `rule_from`, `rule_to`, `str_spare5val`, `module`, `module_status`) values('2',NULL,NULL,NULL,NULL,NULL,'EUR','PKR',NULL,NULL,NULL,'/','*',NULL,NULL,NULL);
insert into `curency_convertor_rule` (`id`, `created_by_user`, `created_datetime`, `updated_by_user`, `updated_datetime`, `curency_convertor_rule`, `currency_to`, `currency_from`, `date_created`, `is_enabled`, `last_updated`, `rule_from`, `rule_to`, `str_spare5val`, `module`, `module_status`) values('3',NULL,NULL,NULL,NULL,NULL,'GBP','PKR',NULL,NULL,NULL,'/','*',NULL,NULL,NULL);
insert into `curency_convertor_rule` (`id`, `created_by_user`, `created_datetime`, `updated_by_user`, `updated_datetime`, `curency_convertor_rule`, `currency_to`, `currency_from`, `date_created`, `is_enabled`, `last_updated`, `rule_from`, `rule_to`, `str_spare5val`, `module`, `module_status`) values('4',NULL,NULL,NULL,NULL,NULL,'AUD','PKR',NULL,NULL,NULL,'/','*',NULL,NULL,NULL);
insert into `curency_convertor_rule` (`id`, `created_by_user`, `created_datetime`, `updated_by_user`, `updated_datetime`, `curency_convertor_rule`, `currency_to`, `currency_from`, `date_created`, `is_enabled`, `last_updated`, `rule_from`, `rule_to`, `str_spare5val`, `module`, `module_status`) values('5',NULL,NULL,NULL,NULL,NULL,'JPY','PKR',NULL,NULL,NULL,'/','*',NULL,NULL,NULL);
insert into `curency_convertor_rule` (`id`, `created_by_user`, `created_datetime`, `updated_by_user`, `updated_datetime`, `curency_convertor_rule`, `currency_to`, `currency_from`, `date_created`, `is_enabled`, `last_updated`, `rule_from`, `rule_to`, `str_spare5val`, `module`, `module_status`) values('6',NULL,NULL,NULL,NULL,NULL,'SGD','PKR',NULL,NULL,NULL,'/','*',NULL,NULL,NULL);
insert into `curency_convertor_rule` (`id`, `created_by_user`, `created_datetime`, `updated_by_user`, `updated_datetime`, `curency_convertor_rule`, `currency_to`, `currency_from`, `date_created`, `is_enabled`, `last_updated`, `rule_from`, `rule_to`, `str_spare5val`, `module`, `module_status`) values('7',NULL,NULL,NULL,NULL,NULL,'CHF','PKR',NULL,NULL,NULL,'/','*',NULL,NULL,NULL);
insert into `curency_convertor_rule` (`id`, `created_by_user`, `created_datetime`, `updated_by_user`, `updated_datetime`, `curency_convertor_rule`, `currency_to`, `currency_from`, `date_created`, `is_enabled`, `last_updated`, `rule_from`, `rule_to`, `str_spare5val`, `module`, `module_status`) values('8',NULL,NULL,NULL,NULL,NULL,'CNY','PKR',NULL,NULL,NULL,'/','*',NULL,NULL,NULL);
insert into `curency_convertor_rule` (`id`, `created_by_user`, `created_datetime`, `updated_by_user`, `updated_datetime`, `curency_convertor_rule`, `currency_to`, `currency_from`, `date_created`, `is_enabled`, `last_updated`, `rule_from`, `rule_to`, `str_spare5val`, `module`, `module_status`) values('9',NULL,NULL,NULL,NULL,NULL,'HKD','PKR',NULL,NULL,NULL,'/','*',NULL,NULL,NULL);
insert into `curency_convertor_rule` (`id`, `created_by_user`, `created_datetime`, `updated_by_user`, `updated_datetime`, `curency_convertor_rule`, `currency_to`, `currency_from`, `date_created`, `is_enabled`, `last_updated`, `rule_from`, `rule_to`, `str_spare5val`, `module`, `module_status`) values('10',NULL,NULL,NULL,NULL,NULL,'AED','PKR',NULL,NULL,NULL,'/','*',NULL,NULL,NULL);
insert into `curency_convertor_rule` (`id`, `created_by_user`, `created_datetime`, `updated_by_user`, `updated_datetime`, `curency_convertor_rule`, `currency_to`, `currency_from`, `date_created`, `is_enabled`, `last_updated`, `rule_from`, `rule_to`, `str_spare5val`, `module`, `module_status`) values('11',NULL,NULL,NULL,NULL,NULL,'SAR','PKR',NULL,NULL,NULL,'/','*',NULL,NULL,NULL);
insert into `curency_convertor_rule` (`id`, `created_by_user`, `created_datetime`, `updated_by_user`, `updated_datetime`, `curency_convertor_rule`, `currency_to`, `currency_from`, `date_created`, `is_enabled`, `last_updated`, `rule_from`, `rule_to`, `str_spare5val`, `module`, `module_status`) values('12',NULL,NULL,NULL,NULL,NULL,'SEK','PKR',NULL,NULL,NULL,'/','*',NULL,NULL,NULL);
